<div class="devils-auth">
    <div class="devils-auth-notice">Login via</div>
    <a title="Facebook" class="devils-auth-btn fb" onclick="Auth.facebook();"><i></i></a>
    <a title="VKontakte" class="devils-auth-btn vk" onclick="Auth.vkontakte();"><i></i></a>
    <a title="Google+" class="devils-auth-btn gl" onclick="Auth.google();"><i></i></a>
    <a title="SoundCloud" class="devils-auth-btn sc" onclick="Auth.soundcloud();"><i></i></a>
</div>