<div class="devils-auth-register">
    <div class="page-title">
        <h1>Register via social</h1>
    </div>
    <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="login-form">
        <?php echo $this->getBlockHtml('formkey'); ?>
        <input type="hidden" name="handler_id" value="<?php echo $this->escapeHtml($this->getFormData()->getHandlerId())?>"/>
        <input type="hidden" name="oa_id" value="<?php echo $this->escapeHtml($this->getFormData()->getOaId())?>"/>
        <input type="hidden" name="oa_access_token" value="<?php echo $this->escapeHtml($this->getFormData()->getOaAccessToken())?>"/>
        <input type="hidden" name="oa_valid_till" value="<?php echo $this->escapeHtml($this->getFormData()->getOaValidTill())?>"/>
        <div class="fieldset">
            <h2 class="legend"><?php echo $this->__('Personal Information') ?></h2>
            <ul class="form-list">
                <li class="fields">
                    <?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getFormData())->setForceUseCustomerAttributes(true)->toHtml() ?>
                </li>
                <li>
                    <label for="email_address" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
                    <div class="input-box">
                        <input type="text" name="email" id="email_address" value="<?php echo $this->escapeHtml($this->getFormData()->getEmail()) ?>" title="<?php echo $this->__('Email Address') ?>" class="input-text validate-email required-entry" />
                    </div>
                </li>
            </ul>
        </div>
        <div class="buttons-set">
            <p class="required"><?php echo $this->__('* Required Fields') ?></p>
            <p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>" class="back-link"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
            <button type="submit" title="<?php echo $this->__('Submit') ?>" class="button"><span><span><?php echo $this->__('Submit') ?></span></span></button>
        </div>
    </form>
</div>